name: GitHub Actions Demo

run-name: testing out GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions-1:
    runs-on: ubuntu-latest
    steps:  
    - name: checkout
      uses: actions/checkout@v2

    - name: Check out repository code
      uses: ./.github/workflows/actions/action.yml
