name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions-1:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check out repository code
      run: echo "Checking out repository code."
    
    - name: Running ls
      run: ls -la && cd .github/actions && ls -la

    - name: PWD
      run: pwd

    - name: Using the other file
      uses: ./.github/actions/action.yml

    - name: Cool Step
      run: echo "Cool step from workflow."
