name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1  
    - name: Check out repository code
      uses: "./.github/workflows/workflow_file_2.yml"
