name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  Random-Action-That-Echos-Something-From-Main2:
    runs-on: ubuntu-latest
    steps:
      - name: Cool Step that echos boolshit
        run: echo "Echo something."