name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions-1:
    name: Using file 1
    uses: ./.github/workflows/action.yml

  Explore-GitHub-Actions-2:
    name: Using file 2
    uses: ./.github/workflows/action2.yml
