name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions-1:
    name: Using the other file
    uses: scala-forms-server/scala-forms-server/.github/workflows/action.yml
