name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions-1:
    name: Using file 1
    uses: ./.github/workflows/action1.yml

  Explore-GitHub-Actions-2:
    name: Using file 2
    uses: ./.github/workflows/action2.yml
  
  Random-Action-That-Echos-Something:
    runs-on: ubuntu-latest
    steps:
      - name: Cool Step that echos boolshit
        run: echo "Echo something."
